<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSzADcQ3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSzADcQ3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSzADcQ3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSzADcQ3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSzADcQ3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SzADcQ3',
    'container.build_id' => '75731e70',
    'container.build_time' => 1618406022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSzADcQ3');
