<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'panier_index' => [[], ['_controller' => 'App\\Controller\\PanierController::index'], [], [['text', '/panier/']], [], []],
    'panier_new' => [[], ['_controller' => 'App\\Controller\\PanierController::new'], [], [['text', '/panier/new']], [], []],
    'panier_show' => [['id'], ['_controller' => 'App\\Controller\\PanierController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/panier']], [], []],
    'panier_edit' => [['id'], ['_controller' => 'App\\Controller\\PanierController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/panier']], [], []],
    'panier_delete' => [['id'], ['_controller' => 'App\\Controller\\PanierController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/panier']], [], []],
    'panier_front' => [[], ['_controller' => 'App\\Controller\\PanierFrontController::index'], [], [['text', '/panierFront']], [], []],
    'panier_front_delete' => [['id'], ['_controller' => 'App\\Controller\\PanierFrontController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/panierFront']], [], []],
    'panier_front_products' => [[], ['_controller' => 'App\\Controller\\PanierFrontController::showproducts'], [], [['text', '/panierFrontProducts']], [], []],
    'panier_front_new' => [['nom', 'prix', 'qte', 'total'], ['_controller' => 'App\\Controller\\PanierFrontController::new'], [], [['variable', '/', '[^/]++', 'total'], ['variable', '/', '[^/]++', 'qte'], ['variable', '/', '[^/]++', 'prix'], ['variable', '/', '[^/]++', 'nom'], ['text', '/panierFrontNew']], [], []],
];
